radicale:
    pm: pip
    package: radicale
    args: "-C {config}/config --auth-htpasswd-filename {config}/users --storage-filesystem-folder {data}/collections"

caddy:
    pm: github_release
    package: caddyserver/caddy
    args: "run --config {config}/Caddyfile"
    env:
        asset-regex: ".*_linux_amd64.tar.gz"

memos:
    pm: github_release
    package: GlowingScrewdriver/memos
    args: "--data {data}"
    env:
        asset-regex: ".*_linux_amd64.tar.gz"

ngrok:
    pm: static_bin
    package: ngrok
    args: start --all --config {config}/ngrok.yml
    env:
        url: https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz
        extractor: tar -zx

sigal:
    pm: pip
    package: sigal
    args: "build -c {config}/sigal.conf.py {export}/digicam-final1 {data}/output"
    periodic: "./sigal build -c {config}/sigal.conf.py {export}/nas/share/digicam-final1/'old photos' {data}/output"
    export:
        - ["{data}/output", "sigal"]

rclone:
    pm: static_bin
    package: rclone
    args: "--config {config}/rclone.conf mount master: {data}/"
    env:
        url: https://downloads.rclone.org/rclone-current-linux-amd64.zip
        extractor: busybox unzip -p - */rclone
    export:
        - ["{data}/nas/", "nas"]

filebrowser:
    pm: github_release
    package: filebrowser/filebrowser
    args: "-d {data}/filebrowser.db -r {export}/nas"
    env:
        asset-regex: "linux-amd64.*"
